### ISSUE TITLE
thread can't be killed while score is being calculated

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold-score#11]
Let's test and fix

**Comment by 0pdd** [comment]
@yegor256 the puzzle [#12](https://github.com/zold-io/zold-score/issues/12) is still not solved.

**Comment by 0crat** [comment]
Job `gh:zold-io/zold-score#11` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0pdd** [comment]
@yegor256 the only puzzle [#12](https://github.com/zold-io/zold-score/issues/12) is solved here.
