### ISSUE TITLE
test_score.rb:182-184: This test is skipped because it...

### ISSUE THREAD

**Issue by 0pdd** [zold-io/zold-score#12]
The puzzle `11-160332e9` from #11 has to be resolved: 

https://github.com/zold-io/zold-score/blob/c56c2ca06ed38728c2018b021e515c636a313849/test/zold/test_score.rb#L182-L184

The puzzle was created by Yegor Bugayenko on 24-Nov-18. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by yegor256** [comment]
@DronMDF can you take a look?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#12](https://github.com/zold-io/zold-score/issues/12) is now in scope, role is `DEV`

**Comment by 0pdd** [comment]
The puzzle `11-160332e9` has disappeared from the source code, that's why I closed this issue.

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.3`

**Comment by 0crat** [comment]
Job `gh:zold-io/zold-score#12` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#12](https://github.com/zold-io/zold-score/issues/12) is now out of scope
