### ISSUE TITLE
Does suffix score reducing affects to next score calculation speed?

### ISSUE THREAD

**Issue by dapi** [zold-io/zold-score#18]
For example: 

We have two same score objects. One reduced and one now.

Does the speed of next score calculation these scores while be same?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dapi[/z](https://www.0crat.com/u/dapi) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@dapi yes, sure, because the `hash` is of the same length

**Comment by 0crat** [comment]
Job `gh:zold-io/zold-score#18` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
