### ISSUE TITLE
Use Time.utc.parse instead to Time.parse in parsing methods

### ISSUE THREAD

**Issue by dapi** [zold-io/zold-score#19]

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dapi[/z](https://www.0crat.com/u/dapi) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@dapi can you please give an example?

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dapi[/z](https://www.0crat.com/u/dapi)

**Comment by dapi** [comment]
here - https://github.com/zold-io/zold-score/blob/17dabf3367cf7e27dac9360e139c26316a755ad4/lib/zold/score.rb#L83

**Comment by dapi** [comment]
@yegor256  Sorry. It was a mistake creating this issue

**Comment by 0crat** [comment]
The job [#19](https://github.com/zold-io/zold-score/issues/19) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)
