### ISSUE TITLE
C/C++ implementation

### ISSUE THREAD

**Issue by yegor256** [zold-io/zold-score#2]
Let's implement score calculation in C/C++.

We tried here: https://github.com/zold-io/zold/pull/223 and here: https://github.com/zold-io/zold/pull/335

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) I'm not managing this repo, remove the [webhook](https://github.com/zold-io/zold-score/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `zold-io/zold-score` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by yegor256** [comment]
@rultor release, tag is `0.3.0`

**Comment by yegor256** [comment]
@DronMDF thanks!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold-score#2` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
