### ISSUE TITLE
Is any reason to have two dumping/restoring methods as to_text/to_s and parse_text/parse

### ISSUE THREAD

**Issue by dapi** [zold-io/zold-score#20]
Probably it will be better to have best one?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dapi[/z](https://www.0crat.com/u/dapi) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@dapi you are right. Let's stay with `to_s` and `parse`

**Comment by yegor256** [comment]
@dapi fixed in b8f469e

**Comment by 0crat** [comment]
Job [#20](https://github.com/zold-io/zold-score/issues/20) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
Job was finished in 0 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dapi[/z](https://www.0crat.com/u/dapi)

**Comment by 0crat** [comment]
The job [#20](https://github.com/zold-io/zold-score/issues/20) is now out of scope
