### ISSUE TITLE
Describe what reducing means in test

### ISSUE THREAD

**Issue by dapi** [zold-io/zold-score#23]
Something like this - https://github.com/zold-io/zold-score/pull/16

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dapi[/z](https://www.0crat.com/u/dapi) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@dapi This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold-score#23` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
