### ISSUE TITLE
Add node_alias method

### ISSUE THREAD

**Issue by dapi** [zold-io/zold-score#29]
Example: 

https://github.com/dapi/zoldy/blob/master/lib/zold/score_ext.rb#L15-L17

Which one is right `node_alias` or `home`? What is difference?

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@dapi[/z](https://www.0crat.com/u/dapi) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CAZPZR9FS) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@dapi  This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
Job `gh:zold-io/zold-score#29` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
